quarkus.http.port=8081

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=velkin
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/tasks
quarkus.hibernate-orm.database.generation=update
quarkus.datasource.db-version=5.7.0

quarkus.http.cors=true
# quarkus.http.cors.origins=${CORS_ORIGINS}
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=location,content-disposition
quarkus.http.cors.access-control-max-age=24H


quarkus.smallrye-openapi.path=/openapi

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui